name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential devscripts debhelper automake # Add more as needed
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
    - name: make dist-zip
      run: make dist-zip

    - name: Build Debian package
      run: |
        dpkg-buildpackage -us -uc -b # Assuming you have a proper debian/ directory structure
        mv ../*.deb .
        mv ../*.changes .
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: deb-package
        path: |
          *.deb
          *.changes
