name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential devscripts debhelper automake # Add more as needed
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck

    - name: Build SSHM Debian Package
      run: |
        dpkg-buildpackage -us -uc -b
        echo "::set-output name=deb_path::./sshm_*.deb"
        mv ../sshm_*.deb .
      id: build

    - name: Upload SSHM Debian Package
      run: |
        curl -X POST \
        -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        -H "Content-Type: application/vnd.debian.package" \
        --data-binary "@${{ steps.build.outputs.deb_path }}" \
        "https://api.github.com/orgs/NikolajHansen/packages/debian/sshm/versions"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}