name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential devscripts debhelper automake # Add more as needed
      - name: configure
        run: ./configure
      - name: make
        run: make
      - name: make check
        run: make check
      - name: make distcheck
        run: make distcheck

      - name: Build SSHM Debian Package
        run: |
          dpkg-buildpackage -us -uc -b
          sudo mkdir -p ./build
          sudo chmod 755 ./build
          mv ../*.deb ./build/
          echo "::set-output name=deb_path::./build/sshm_*.deb"
        id: build_deb