name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential devscripts debhelper automake

      - name: configure
        run: ./configure

      - name: make
        run: make

      - name: make check
        run: make check

      - name: make distcheck
        run: make distcheck

      - name: Build SSHM Debian Package
        id: build
        run: |
          dpkg-buildpackage -us -uc -b
          mkdir -p artifacts
          mv ../sshm_*.deb artifacts/
          echo "deb_path=artifacts/sshm_*.deb" >> $GITHUB_OUTPUT

      - name: Upload SSHM Debian Package
        uses: actions/upload-artifact@v4
        with:
          name: sshm-debian-packages
          path: ${{ steps.build.outputs.deb_path }}